name: car_price

services:
  price-classifier:
    image: car_price_model:1
    ports:
      - "8000:8000"
    volumes:
      - ./models:/models


  requests:
    image: req:0
    deploy: 
      replicas: 1
      restart_policy:
        condition: always
        delay: 5s