name: lr_4

services:
  price-classifier:
    image: lr_3_model:0
    ports:
      - "8000:8000"
    volumes:
      - ./models:/models


  requests:
    image: req:0
    deploy: 
      replicas: 1
      restart_policy:
        condition: always
        delay: 5s